apiVersion: v1
kind: ConfigMap
metadata:
  name: periodicpi-defaults
  labels:
    app: periodicpi
data:
  SPARK_DRIVER_MEMORY: 1g
  SPARK_EXECUTOR_INSTANCES: "2"
  NUM_SAMPLES: "50000"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: periodicpi
  labels:
    app: periodicpi
spec:
  concurrencyPolicy: "Forbid"
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: periodicpi
        spark-role: driver
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: spark-kubernetes-driver
            image: periodicpi:dev
            terminationMessagePolicy: FallbackToLogsOnError
            args: []
            envFrom:
            - configMapRef: {optional: false, name: periodicpi-defaults}
            - configMapRef: {optional: true,  name: periodicpi-overrides}
            resources:
              limits: {memory: 1408Mi}
              requests: {cpu: "1", memory: 1Gi}